---
- name: Install Apache on Debian-based systems
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Deploy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    force: yes

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: true
